version: "3.9"
services:
  app:
    build: .
    container_name: la-rosalina-assistant
    ports:
      - "8501:8501"
    env_file:
      - .env               
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      retries: 3
